# FROM debian:stretch-slim
# RUN apt-get update \
# && apt-get install -y --no-install-recommends git python3\
# && apt-get clean

FROM python:3.8.14
RUN apt-get update
RUN apt-get install -y gfortran
RUN pip install --no-cache -U numpy scipy numba ultranest
RUN pip install --no-cache -U NumbaMinpack 
